sonar.projectKey=Haaragard_fc-ci-sonarcloud-js
sonar.organization=haaragard
#sonar.projectKey=fc-ci-sonarcloud-js
#sonar.projectName=fc-ci-sonarcloud-js
#sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.source.inclusions=**/*.js
sonar.exclusions=

sonar.tests=test
sonar.test.inclusions=**/*.test.js
sonar.javascript.coveragePlugin=lcov
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# For local use only
#sonar.login=sqp_8548905d7bbdecd60254d542114141003658895d
#sonar.host.url=http://localhost:9000
